package io.github.sgtswagrid.nonsense
package groups.builder

import io.github.sgtswagrid.nonsense.groups.ordered.builder.OrderedMultiplicativeSemigroupBuilder

trait MultiplicativeSemigroupBuilder extends OrderedMultiplicativeSemigroupBuilder, MultiplicativeMonoidBuilder
