package io.github.sgtswagrid.nonsense
package groups.builder

import io.github.sgtswagrid.nonsense.groups.ordered.builder.OrderedMultiplicativeMonoidBuilder

trait MultiplicativeMonoidBuilder extends OrderedMultiplicativeMonoidBuilder, EuclideanMonoidBuilder
